// GENERATED FILE PLACEHOLDER.
// Do NOT edit this file manually for production.
// Run: flutterfire configure
// It will replace this file with your real Firebase project configuration.
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Run flutterfire configure for Web if needed.');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android: throw UnsupportedError('Run flutterfire configure to generate Android FirebaseOptions.');
      default: throw UnsupportedError('Platform not configured.');
    }
  }
}
